# Generated by Django 2.2.2 on 2019-06-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functionname', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
