# Generated by Django 2.2.2 on 2019-06-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190613_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionsavailable',
            name='authorname',
        ),
    ]
